name: 'Katana CI'
description: 'Starts a Katana by interacting with a katana-ci-server.'
inputs:
  api-url:
    description: 'API URL of the katana-ci-server'
    required: true
  api-key:
    description: 'API KEY to start a Katana'
    required: true
  cmd:
    description: 'The command (start or stop) to be executed'
    required: true
  name:
    description: 'The name of the instance, if known'
    required: false
    default: ''

outputs:
  katana-name:
    description: 'The name of the Katana started on the server'
  katana-rpc:
    description: 'The RPC URL to use the newly created instance'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.api-url }}
    - ${{ inputs.api-key }}
    - ${{ inputs.cmd }}
    - ${{ inputs.name }}
